title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- assets
- .github
ext:
- go
- tmpl
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go
  after:
  - ps -ef|grep 'go-p2p-server service'| grep -v grep | awk '{print $2}' | xargs kill -9  && ./go-p2p-server service &
link: https://github.com/midoks/zzz
